# -*- coding: utf-8 -*-
"""Financial Stock Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9KXk-rdbssP0-9GQSJzviBwp0w4-W1u
"""

import sklearn as sk
import numpy as np
import pandas as pd #importing libraries
import seaborn as sb
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/tech-stock-2019-2024.csv' #defining the path to the data set
df = pd.read_csv(file_path)

#visualization using seaborn
sb.relplot(
    data=df,
    x="Volume", y="Adj Close",
)

"""Non-linear regression"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df = df[df['Volume'] > 0]  # Ensure no log(0) or log of negative

# Transform feature
X = -np.log(df[['Volume']].values)
y = df[['Adj Close']].values

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Fit the linear model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict and evaluate
y_pred_test = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred_test)
r2 = r2_score(y_test, y_pred_test)
print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r2}")

# Plot prediction vs actual
plt.scatter(y_test, y_pred_test)
plt.xlabel("Actual Adj Close")
plt.ylabel("Predicted Adj Close")
plt.title("Actual vs Predicted Adj Close using -log(Volume)")
plt.grid(True)
plt.show()

"""Decision Tree"""

from sklearn.model_selection import train_test_split

X = df[['Volume']]
y = df[['Adj Close']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

regr_1 = DecisionTreeRegressor(max_depth=4)
regr_2 = AdaBoostRegressor(DecisionTreeRegressor(max_depth=4), n_estimators=300)

regr_1.fit(X_train, y_train)
regr_2.fit(X_train, y_train)

y_pred_1 = regr_1.predict(X_test)
y_pred_2 = regr_2.predict(X_test)

# Accuracy on test data
print("Test Accuracy:\n")
print("Decision Tree R2:", r2_score(y_test, y_pred_1))
print("AdaBoost R2:", r2_score(y_test, y_pred_2))

colors = sb.color_palette("colorblind")

plt.figure()
plt.scatter(X, y, color=colors[0], label="training samples")
plt.scatter(X, y_1, color=colors[1], label="n_estimators=1", linewidth=2)
plt.scatter(X, y_2, color=colors[2], label="n_estimators=300", linewidth=2)
plt.xlabel("volume")
plt.ylabel("closing price")
plt.title("Boosted Decision Tree Regression")
plt.legend()
plt.show()

"""Random Forest"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, mean_squared_error

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
rmse = mean_squared_error(y_test, y_pred_test)
print(f"RMSE: {rmse}")

from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(estimator=RandomForestRegressor(random_state=42),
                           param_grid=param_grid,
                           cv=5,
                           scoring='accuracy',
                           n_jobs=-1)

grid_search.fit(X_train, y_train)
print(f"Best parameters: {grid_search.best_params_}")
print(f"Best score: {grid_search.best_score_}")

"""Heatmap to find correlated varriables"""

import seaborn as sb
import matplotlib.pyplot as plt


columns_to_drop = ['Date', 'Ticker']
df_nodate = df.drop(columns=columns_to_drop)

correlation_matrix = df_nodate.corr()

sb.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")

plt.title("Correlation Matrix Heatmap")
plt.show()